name: Test/DummyFail

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment (only the 'master' branch can deploy to 'prod')
        options:
          - test
          - prod
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Not Implemented Yet
        run: exit 1
